# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Optional, Union
from typing_extensions import Annotated
from openapi_client.models.cost_estimate_response import CostEstimateResponse
from openapi_client.models.eta_estimate_response import EtaEstimateResponse
from openapi_client.models.nearby_drivers_response import NearbyDriversResponse
from openapi_client.models.ride_types_response import RideTypesResponse

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class PublicApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_cost(
        self,
        start_lat: Annotated[Union[StrictFloat, StrictInt], Field(description="Latitude of the starting location")],
        start_lng: Annotated[Union[StrictFloat, StrictInt], Field(description="Longitude of the starting location")],
        ride_type: Annotated[Optional[StrictStr], Field(description="ID of a ride type")] = None,
        end_lat: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Latitude of the ending location")] = None,
        end_lng: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Longitude of the ending location")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CostEstimateResponse:
        """Cost estimates

        Estimate the cost of taking a Lyft between two points. 

        :param start_lat: Latitude of the starting location (required)
        :type start_lat: float
        :param start_lng: Longitude of the starting location (required)
        :type start_lng: float
        :param ride_type: ID of a ride type
        :type ride_type: str
        :param end_lat: Latitude of the ending location
        :type end_lat: float
        :param end_lng: Longitude of the ending location
        :type end_lng: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_cost_serialize(
            start_lat=start_lat,
            start_lng=start_lng,
            ride_type=ride_type,
            end_lat=end_lat,
            end_lng=end_lng,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CostEstimateResponse",
            '400': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_cost_with_http_info(
        self,
        start_lat: Annotated[Union[StrictFloat, StrictInt], Field(description="Latitude of the starting location")],
        start_lng: Annotated[Union[StrictFloat, StrictInt], Field(description="Longitude of the starting location")],
        ride_type: Annotated[Optional[StrictStr], Field(description="ID of a ride type")] = None,
        end_lat: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Latitude of the ending location")] = None,
        end_lng: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Longitude of the ending location")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CostEstimateResponse]:
        """Cost estimates

        Estimate the cost of taking a Lyft between two points. 

        :param start_lat: Latitude of the starting location (required)
        :type start_lat: float
        :param start_lng: Longitude of the starting location (required)
        :type start_lng: float
        :param ride_type: ID of a ride type
        :type ride_type: str
        :param end_lat: Latitude of the ending location
        :type end_lat: float
        :param end_lng: Longitude of the ending location
        :type end_lng: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_cost_serialize(
            start_lat=start_lat,
            start_lng=start_lng,
            ride_type=ride_type,
            end_lat=end_lat,
            end_lng=end_lng,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CostEstimateResponse",
            '400': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_cost_without_preload_content(
        self,
        start_lat: Annotated[Union[StrictFloat, StrictInt], Field(description="Latitude of the starting location")],
        start_lng: Annotated[Union[StrictFloat, StrictInt], Field(description="Longitude of the starting location")],
        ride_type: Annotated[Optional[StrictStr], Field(description="ID of a ride type")] = None,
        end_lat: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Latitude of the ending location")] = None,
        end_lng: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Longitude of the ending location")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Cost estimates

        Estimate the cost of taking a Lyft between two points. 

        :param start_lat: Latitude of the starting location (required)
        :type start_lat: float
        :param start_lng: Longitude of the starting location (required)
        :type start_lng: float
        :param ride_type: ID of a ride type
        :type ride_type: str
        :param end_lat: Latitude of the ending location
        :type end_lat: float
        :param end_lng: Longitude of the ending location
        :type end_lng: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_cost_serialize(
            start_lat=start_lat,
            start_lng=start_lng,
            ride_type=ride_type,
            end_lat=end_lat,
            end_lng=end_lng,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CostEstimateResponse",
            '400': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_cost_serialize(
        self,
        start_lat,
        start_lng,
        ride_type,
        end_lat,
        end_lng,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if ride_type is not None:
            
            _query_params.append(('ride_type', ride_type))
            
        if start_lat is not None:
            
            _query_params.append(('start_lat', start_lat))
            
        if start_lng is not None:
            
            _query_params.append(('start_lng', start_lng))
            
        if end_lat is not None:
            
            _query_params.append(('end_lat', end_lat))
            
        if end_lng is not None:
            
            _query_params.append(('end_lng', end_lng))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'User_Authentication', 
            'Client_Authentication'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/cost',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_drivers(
        self,
        lat: Annotated[Union[StrictFloat, StrictInt], Field(description="Latitude of a location")],
        lng: Annotated[Union[StrictFloat, StrictInt], Field(description="Longitude of a location")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> NearbyDriversResponse:
        """Available drivers nearby

        The drivers endpoint returns a list of nearby drivers' lat and lng at a given location. 

        :param lat: Latitude of a location (required)
        :type lat: float
        :param lng: Longitude of a location (required)
        :type lng: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_drivers_serialize(
            lat=lat,
            lng=lng,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NearbyDriversResponse",
            '400': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_drivers_with_http_info(
        self,
        lat: Annotated[Union[StrictFloat, StrictInt], Field(description="Latitude of a location")],
        lng: Annotated[Union[StrictFloat, StrictInt], Field(description="Longitude of a location")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[NearbyDriversResponse]:
        """Available drivers nearby

        The drivers endpoint returns a list of nearby drivers' lat and lng at a given location. 

        :param lat: Latitude of a location (required)
        :type lat: float
        :param lng: Longitude of a location (required)
        :type lng: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_drivers_serialize(
            lat=lat,
            lng=lng,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NearbyDriversResponse",
            '400': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_drivers_without_preload_content(
        self,
        lat: Annotated[Union[StrictFloat, StrictInt], Field(description="Latitude of a location")],
        lng: Annotated[Union[StrictFloat, StrictInt], Field(description="Longitude of a location")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Available drivers nearby

        The drivers endpoint returns a list of nearby drivers' lat and lng at a given location. 

        :param lat: Latitude of a location (required)
        :type lat: float
        :param lng: Longitude of a location (required)
        :type lng: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_drivers_serialize(
            lat=lat,
            lng=lng,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NearbyDriversResponse",
            '400': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_drivers_serialize(
        self,
        lat,
        lng,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if lat is not None:
            
            _query_params.append(('lat', lat))
            
        if lng is not None:
            
            _query_params.append(('lng', lng))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'User_Authentication', 
            'Client_Authentication'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/drivers',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_eta(
        self,
        lat: Annotated[Union[StrictFloat, StrictInt], Field(description="Latitude of a location")],
        lng: Annotated[Union[StrictFloat, StrictInt], Field(description="Longitude of a location")],
        destination_lat: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Latitude of destination location")] = None,
        destination_lng: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Longitude of destination location")] = None,
        ride_type: Annotated[Optional[StrictStr], Field(description="ID of a ride type")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> EtaEstimateResponse:
        """Pickup ETAs

        The ETA endpoint lets you know how quickly a Lyft driver can come get you 

        :param lat: Latitude of a location (required)
        :type lat: float
        :param lng: Longitude of a location (required)
        :type lng: float
        :param destination_lat: Latitude of destination location
        :type destination_lat: float
        :param destination_lng: Longitude of destination location
        :type destination_lng: float
        :param ride_type: ID of a ride type
        :type ride_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_eta_serialize(
            lat=lat,
            lng=lng,
            destination_lat=destination_lat,
            destination_lng=destination_lng,
            ride_type=ride_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EtaEstimateResponse",
            '400': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_eta_with_http_info(
        self,
        lat: Annotated[Union[StrictFloat, StrictInt], Field(description="Latitude of a location")],
        lng: Annotated[Union[StrictFloat, StrictInt], Field(description="Longitude of a location")],
        destination_lat: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Latitude of destination location")] = None,
        destination_lng: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Longitude of destination location")] = None,
        ride_type: Annotated[Optional[StrictStr], Field(description="ID of a ride type")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[EtaEstimateResponse]:
        """Pickup ETAs

        The ETA endpoint lets you know how quickly a Lyft driver can come get you 

        :param lat: Latitude of a location (required)
        :type lat: float
        :param lng: Longitude of a location (required)
        :type lng: float
        :param destination_lat: Latitude of destination location
        :type destination_lat: float
        :param destination_lng: Longitude of destination location
        :type destination_lng: float
        :param ride_type: ID of a ride type
        :type ride_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_eta_serialize(
            lat=lat,
            lng=lng,
            destination_lat=destination_lat,
            destination_lng=destination_lng,
            ride_type=ride_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EtaEstimateResponse",
            '400': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_eta_without_preload_content(
        self,
        lat: Annotated[Union[StrictFloat, StrictInt], Field(description="Latitude of a location")],
        lng: Annotated[Union[StrictFloat, StrictInt], Field(description="Longitude of a location")],
        destination_lat: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Latitude of destination location")] = None,
        destination_lng: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Longitude of destination location")] = None,
        ride_type: Annotated[Optional[StrictStr], Field(description="ID of a ride type")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Pickup ETAs

        The ETA endpoint lets you know how quickly a Lyft driver can come get you 

        :param lat: Latitude of a location (required)
        :type lat: float
        :param lng: Longitude of a location (required)
        :type lng: float
        :param destination_lat: Latitude of destination location
        :type destination_lat: float
        :param destination_lng: Longitude of destination location
        :type destination_lng: float
        :param ride_type: ID of a ride type
        :type ride_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_eta_serialize(
            lat=lat,
            lng=lng,
            destination_lat=destination_lat,
            destination_lng=destination_lng,
            ride_type=ride_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EtaEstimateResponse",
            '400': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_eta_serialize(
        self,
        lat,
        lng,
        destination_lat,
        destination_lng,
        ride_type,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if lat is not None:
            
            _query_params.append(('lat', lat))
            
        if lng is not None:
            
            _query_params.append(('lng', lng))
            
        if destination_lat is not None:
            
            _query_params.append(('destination_lat', destination_lat))
            
        if destination_lng is not None:
            
            _query_params.append(('destination_lng', destination_lng))
            
        if ride_type is not None:
            
            _query_params.append(('ride_type', ride_type))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'User_Authentication', 
            'Client_Authentication'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/eta',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_ride_types(
        self,
        lat: Annotated[Union[StrictFloat, StrictInt], Field(description="Latitude of a location")],
        lng: Annotated[Union[StrictFloat, StrictInt], Field(description="Longitude of a location")],
        ride_type: Annotated[Optional[StrictStr], Field(description="ID of a ride type")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RideTypesResponse:
        """Types of rides

        The ride types endpoint returns information about what kinds of Lyft rides you can request at a given location. 

        :param lat: Latitude of a location (required)
        :type lat: float
        :param lng: Longitude of a location (required)
        :type lng: float
        :param ride_type: ID of a ride type
        :type ride_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_ride_types_serialize(
            lat=lat,
            lng=lng,
            ride_type=ride_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RideTypesResponse",
            '400': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_ride_types_with_http_info(
        self,
        lat: Annotated[Union[StrictFloat, StrictInt], Field(description="Latitude of a location")],
        lng: Annotated[Union[StrictFloat, StrictInt], Field(description="Longitude of a location")],
        ride_type: Annotated[Optional[StrictStr], Field(description="ID of a ride type")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[RideTypesResponse]:
        """Types of rides

        The ride types endpoint returns information about what kinds of Lyft rides you can request at a given location. 

        :param lat: Latitude of a location (required)
        :type lat: float
        :param lng: Longitude of a location (required)
        :type lng: float
        :param ride_type: ID of a ride type
        :type ride_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_ride_types_serialize(
            lat=lat,
            lng=lng,
            ride_type=ride_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RideTypesResponse",
            '400': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_ride_types_without_preload_content(
        self,
        lat: Annotated[Union[StrictFloat, StrictInt], Field(description="Latitude of a location")],
        lng: Annotated[Union[StrictFloat, StrictInt], Field(description="Longitude of a location")],
        ride_type: Annotated[Optional[StrictStr], Field(description="ID of a ride type")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Types of rides

        The ride types endpoint returns information about what kinds of Lyft rides you can request at a given location. 

        :param lat: Latitude of a location (required)
        :type lat: float
        :param lng: Longitude of a location (required)
        :type lng: float
        :param ride_type: ID of a ride type
        :type ride_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_ride_types_serialize(
            lat=lat,
            lng=lng,
            ride_type=ride_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RideTypesResponse",
            '400': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_ride_types_serialize(
        self,
        lat,
        lng,
        ride_type,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if lat is not None:
            
            _query_params.append(('lat', lat))
            
        if lng is not None:
            
            _query_params.append(('lng', lng))
            
        if ride_type is not None:
            
            _query_params.append(('ride_type', ride_type))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'User_Authentication', 
            'Client_Authentication'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/ridetypes',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


