# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.nearby_driver import NearbyDriver
from typing import Optional, Set
from typing_extensions import Self

class NearbyDriversByRideType(BaseModel):
    """
    NearbyDriversByRideType
    """ # noqa: E501
    drivers: Optional[List[NearbyDriver]] = Field(default=None, description="list of nearby drivers group by ride type sorted by eta")
    ride_type: Optional[StrictStr] = Field(default=None, description="driver's ride type. if driver is eligable for several ride types, he will be duplicated.")
    __properties: ClassVar[List[str]] = ["drivers", "ride_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NearbyDriversByRideType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in drivers (list)
        _items = []
        if self.drivers:
            for _item_drivers in self.drivers:
                if _item_drivers:
                    _items.append(_item_drivers.to_dict())
            _dict['drivers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NearbyDriversByRideType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "drivers": [NearbyDriver.from_dict(_item) for _item in obj["drivers"]] if obj.get("drivers") is not None else None,
            "ride_type": obj.get("ride_type")
        })
        return _obj


