# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RideTypeEnumWithOther(str, Enum):
    """
    The ID of the ride type
    """

    """
    allowed enum values
    """
    LYFT = 'lyft'
    LYFT_LINE = 'lyft_line'
    LYFT_PLUS = 'lyft_plus'
    LYFT_PREMIER = 'lyft_premier'
    LYFT_LUX = 'lyft_lux'
    LYFT_LUXSUV = 'lyft_luxsuv'
    OTHER = 'other'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RideTypeEnumWithOther from a JSON string"""
        return cls(json.loads(json_str))


