# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.location import Location
from openapi_client.models.passenger_detail import PassengerDetail
from openapi_client.models.ride_status_enum import RideStatusEnum
from typing import Optional, Set
from typing_extensions import Self

class RideRequest(BaseModel):
    """
    Minimal set of ride details
    """ # noqa: E501
    destination: Optional[Location] = Field(default=None, description="The *requested* location for passenger drop off")
    origin: Optional[Location] = Field(default=None, description="The *requested* location for passenger pickup")
    passenger: Optional[PassengerDetail] = None
    ride_id: Optional[StrictStr] = Field(default=None, description="The ID of the requested ride")
    status: Optional[RideStatusEnum] = None
    __properties: ClassVar[List[str]] = ["destination", "origin", "passenger", "ride_id", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RideRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of destination
        if self.destination:
            _dict['destination'] = self.destination.to_dict()
        # override the default output from pydantic by calling `to_dict()` of origin
        if self.origin:
            _dict['origin'] = self.origin.to_dict()
        # override the default output from pydantic by calling `to_dict()` of passenger
        if self.passenger:
            _dict['passenger'] = self.passenger.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RideRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "destination": Location.from_dict(obj["destination"]) if obj.get("destination") is not None else None,
            "origin": Location.from_dict(obj["origin"]) if obj.get("origin") is not None else None,
            "passenger": PassengerDetail.from_dict(obj["passenger"]) if obj.get("passenger") is not None else None,
            "ride_id": obj.get("ride_id"),
            "status": obj.get("status")
        })
        return _obj


