# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RideStatusEnum(str, Enum):
    """
    The status of the ride
    """

    """
    allowed enum values
    """
    PENDING = 'pending'
    ACCEPTED = 'accepted'
    ARRIVED = 'arrived'
    PICKEDUP = 'pickedUp'
    DROPPEDOFF = 'droppedOff'
    CANCELED = 'canceled'
    SCHEDULED = 'scheduled'
    UNKNOWN = 'unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RideStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


