# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.eta_estimate_response import EtaEstimateResponse

class TestEtaEstimateResponse(unittest.TestCase):
    """EtaEstimateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EtaEstimateResponse:
        """Test EtaEstimateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EtaEstimateResponse`
        """
        model = EtaEstimateResponse()
        if include_optional:
            return EtaEstimateResponse(
                eta_estimates = [
                    {"display_name":"Lyft Line","eta_seconds":120,"is_valid_estimate":true,"ride_type":"lyft_line"}
                    ]
            )
        else:
            return EtaEstimateResponse(
        )
        """

    def testEtaEstimateResponse(self):
        """Test EtaEstimateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
