# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ride_receipt import RideReceipt

class TestRideReceipt(unittest.TestCase):
    """RideReceipt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RideReceipt:
        """Test RideReceipt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RideReceipt`
        """
        model = RideReceipt()
        if include_optional:
            return RideReceipt(
                charges = [
                    openapi_client.models.charge.Charge(
                        amount = 56, 
                        currency = '', 
                        payment_method = '', )
                    ],
                line_items = [
                    openapi_client.models.line_item.LineItem(
                        amount = 56, 
                        currency = '', 
                        type = '', )
                    ],
                price = {"amount":500,"currency":"USD","description":"Total cost"},
                requested_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ride_id = '',
                ride_profile = 'personal'
            )
        else:
            return RideReceipt(
        )
        """

    def testRideReceipt(self):
        """Test RideReceipt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
