# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.nearby_drivers_response import NearbyDriversResponse

class TestNearbyDriversResponse(unittest.TestCase):
    """NearbyDriversResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NearbyDriversResponse:
        """Test NearbyDriversResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NearbyDriversResponse`
        """
        model = NearbyDriversResponse()
        if include_optional:
            return NearbyDriversResponse(
                nearby_drivers = [
                    openapi_client.models.nearby_drivers_by_ride_type.NearbyDriversByRideType(
                        drivers = [
                            openapi_client.models.nearby_driver.NearbyDriver(
                                locations = [
                                    {"lat":36.9442175,"lng":-123.8679133}
                                    ], )
                            ], 
                        ride_type = '', )
                    ]
            )
        else:
            return NearbyDriversResponse(
        )
        """

    def testNearbyDriversResponse(self):
        """Test NearbyDriversResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
