# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cost_estimate_response import CostEstimateResponse

class TestCostEstimateResponse(unittest.TestCase):
    """CostEstimateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CostEstimateResponse:
        """Test CostEstimateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CostEstimateResponse`
        """
        model = CostEstimateResponse()
        if include_optional:
            return CostEstimateResponse(
                cost_estimates = [
                    {"cost_token":"EupdCgIzy17lJoRmiO5","display_name":"Lyft","estimated_cost_cents_max":1080,"estimated_cost_cents_min":1390,"estimated_distance_miles":12.4,"estimated_duration_seconds":540,"is_valid_estimate":true,"primetime_confirmation_token":"EupdCgIzy17lJoRmiO5","primetime_percentage":"25%","ride_type":"lyft"}
                    ]
            )
        else:
            return CostEstimateResponse(
        )
        """

    def testCostEstimateResponse(self):
        """Test CostEstimateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
