# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ride_types_response import RideTypesResponse

class TestRideTypesResponse(unittest.TestCase):
    """RideTypesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RideTypesResponse:
        """Test RideTypesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RideTypesResponse`
        """
        model = RideTypesResponse()
        if include_optional:
            return RideTypesResponse(
                ride_types = [
                    {"ride_types":[{"display_name":"Lyft Line","image_url":"https://cdn.lyft.com/assets/car_standard.png","pricing_details":{"base_charge":200,"cancel_penalty_amount":500,"cost_minimum":475,"cost_per_mile":115,"cost_per_minute":23,"currency":"USD","trust_and_service":155},"ride_type":"lyft_line","seats":2},{"display_name":"Lyft","image_url":"https://cdn.lyft.com/assets/car_standard.png","pricing_details":{"base_charge":200,"cancel_penalty_amount":500,"cost_minimum":500,"cost_per_mile":115,"cost_per_minute":23,"currency":"USD","trust_and_service":155},"ride_type":"lyft","seats":4},{"display_name":"Lyft Plus","image_url":"https://cdn.lyft.com/assets/car_plus.png","pricing_details":{"base_charge":300,"cancel_penalty_amount":500,"cost_minimum":700,"cost_per_mile":200,"cost_per_minute":30,"currency":"USD","trust_and_service":155},"ride_type":"lyft_plus","seats":6}]}
                    ]
            )
        else:
            return RideTypesResponse(
        )
        """

    def testRideTypesResponse(self):
        """Test RideTypesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
