# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ride_type import RideType

class TestRideType(unittest.TestCase):
    """RideType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RideType:
        """Test RideType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RideType`
        """
        model = RideType()
        if include_optional:
            return RideType(
                display_name = '',
                image_url = '',
                pricing_details = {"base_charge":175,"cancel_penalty_amount":500,"cost_minumum":500,"cost_per_mile":116,"cost_per_minute":23,"currency":"USD","trust_and_service":155},
                ride_type = 'lyft',
                scheduled_pricing_details = {"base_charge":175,"cancel_penalty_amount":500,"cost_minumum":500,"cost_per_mile":116,"cost_per_minute":23,"currency":"USD","trust_and_service":155},
                seats = 56
            )
        else:
            return RideType(
        )
        """

    def testRideType(self):
        """Test RideType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
