# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ride_type_enum_with_other import RideTypeEnumWithOther

class TestRideTypeEnumWithOther(unittest.TestCase):
    """RideTypeEnumWithOther unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRideTypeEnumWithOther(self):
        """Test RideTypeEnumWithOther"""
        # inst = RideTypeEnumWithOther()

if __name__ == '__main__':
    unittest.main()
