# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rides_response import RidesResponse

class TestRidesResponse(unittest.TestCase):
    """RidesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RidesResponse:
        """Test RidesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RidesResponse`
        """
        model = RidesResponse()
        if include_optional:
            return RidesResponse(
                ride_history = [
                    {"beacon_color":"#FFFFFF","destination":{"address":"987 Second St, Anytown, CA","lat":36.9453452,"lng":-123.8642521},"distance_miles":16.2,"driver":{"first_name":"Joe","image_url":"http://example.com/lyft.png","phone_number":"+15554445111","rating":"4.9"},"dropoff":{"address":"987 Second St, Anytown, CA","lat":36.9453452,"lng":-123.8642521,"time":"2015-09-24T23:28:25.000Z"},"duration_seconds":1620,"line_items":[{"amount":500,"currency":"USD","type":"Ride"},{"amount":250,"currency":"USD","type":"Prime Time"},{"amount":155,"currency":"USD","type":"Service fee"}],"location":{"address":"987 Second St, Anytown, CA","lat":36.9453452,"lng":-123.8642521},"origin":{"address":"123 Main St, Anytown, CA","lat":36.9442175,"lng":-123.8679133},"passenger":{"first_name":"Jane","phone_number":"+15554445000","user_id":"776630198662493392"},"pickup":{"address":"123 Main St, Anytown, CA","lat":36.9442175,"lng":-123.8679133,"time":"2015-09-24T23:27:25.000Z"},"price":{"amount":905,"currency":"USD","description":"Total ride price"},"primetime_percentage":"50%","requested_at":"2015-09-24T23:26:25.000Z","ride_id":123456789,"ride_profile":"personal","ride_type":"lyft","status":"droppedOff","vehicle":{"color":"black","image_url":"http://example.com/lyft.png","license_plate":"AAAAAAA","make":"Audi","model":"A4"}}
                    ]
            )
        else:
            return RidesResponse(
        )
        """

    def testRidesResponse(self):
        """Test RidesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
