# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ride_request_error import RideRequestError

class TestRideRequestError(unittest.TestCase):
    """RideRequestError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RideRequestError:
        """Test RideRequestError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RideRequestError`
        """
        model = RideRequestError()
        if include_optional:
            return RideRequestError(
                cost_token = '',
                error = '',
                error_description = '',
                error_detail = [
                    {"lat":"(latitude) Missing required parameter in the query string"}
                    ],
                error_uri = '',
                primetime_confirmation_token = '',
                primetime_multiplier = 1.337,
                primetime_percentage = '',
                token_duration = ''
            )
        else:
            return RideRequestError(
                error = '',
        )
        """

    def testRideRequestError(self):
        """Test RideRequestError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
