# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ride_profile_enum import RideProfileEnum

class TestRideProfileEnum(unittest.TestCase):
    """RideProfileEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRideProfileEnum(self):
        """Test RideProfileEnum"""
        # inst = RideProfileEnum()

if __name__ == '__main__':
    unittest.main()
