# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.public_api import PublicApi


class TestPublicApi(unittest.TestCase):
    """PublicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PublicApi()

    def tearDown(self) -> None:
        pass

    def test_get_cost(self) -> None:
        """Test case for get_cost

        Cost estimates
        """
        pass

    def test_get_drivers(self) -> None:
        """Test case for get_drivers

        Available drivers nearby
        """
        pass

    def test_get_eta(self) -> None:
        """Test case for get_eta

        Pickup ETAs
        """
        pass

    def test_get_ride_types(self) -> None:
        """Test case for get_ride_types

        Types of rides
        """
        pass


if __name__ == '__main__':
    unittest.main()
