# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.sandbox_api import SandboxApi


class TestSandboxApi(unittest.TestCase):
    """SandboxApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SandboxApi()

    def tearDown(self) -> None:
        pass

    def test_set_prime_time(self) -> None:
        """Test case for set_prime_time

        Preset Prime Time percentage
        """
        pass

    def test_set_ride_status(self) -> None:
        """Test case for set_ride_status

        Propagate ride through ride status
        """
        pass

    def test_set_ride_type_availability(self) -> None:
        """Test case for set_ride_type_availability

        Driver availability for processing ride request
        """
        pass

    def test_set_ride_types(self) -> None:
        """Test case for set_ride_types

        Preset types of rides for sandbox
        """
        pass


if __name__ == '__main__':
    unittest.main()
