# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ride import Ride

class TestRide(unittest.TestCase):
    """Ride unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ride:
        """Test Ride
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Ride`
        """
        model = Ride()
        if include_optional:
            return Ride(
                cost_token = '',
                destination = {"address":"123 Main St, Anytown, CA","lat":36.9442175,"lng":-123.8679133},
                origin = {"address":"123 Main St, Anytown, CA","lat":36.9442175,"lng":-123.8679133},
                primetime_confirmation_token = '',
                ride_type = 'lyft'
            )
        else:
            return Ride(
                origin = {"address":"123 Main St, Anytown, CA","lat":36.9442175,"lng":-123.8679133},
                ride_type = 'lyft',
        )
        """

    def testRide(self):
        """Test Ride"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
