# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sandbox_driver_availability import SandboxDriverAvailability

class TestSandboxDriverAvailability(unittest.TestCase):
    """SandboxDriverAvailability unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SandboxDriverAvailability:
        """Test SandboxDriverAvailability
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SandboxDriverAvailability`
        """
        model = SandboxDriverAvailability()
        if include_optional:
            return SandboxDriverAvailability(
                driver_availability = True,
                lat = 1.337,
                lng = 1.337
            )
        else:
            return SandboxDriverAvailability(
                driver_availability = True,
                lat = 1.337,
                lng = 1.337,
        )
        """

    def testSandboxDriverAvailability(self):
        """Test SandboxDriverAvailability"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
