# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ride_request import RideRequest

class TestRideRequest(unittest.TestCase):
    """RideRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RideRequest:
        """Test RideRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RideRequest`
        """
        model = RideRequest()
        if include_optional:
            return RideRequest(
                destination = {"address":"123 Main St, Anytown, CA","lat":36.9442175,"lng":-123.8679133},
                origin = {"address":"123 Main St, Anytown, CA","lat":36.9442175,"lng":-123.8679133},
                passenger = {"first_name":"Jane","image_url":"https://public-api.lyft.com/static/images/user.png","last_name":"Doe","rating":4.9},
                ride_id = '',
                status = 'pending'
            )
        else:
            return RideRequest(
        )
        """

    def testRideRequest(self):
        """Test RideRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
