# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pricing_details import PricingDetails

class TestPricingDetails(unittest.TestCase):
    """PricingDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PricingDetails:
        """Test PricingDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PricingDetails`
        """
        model = PricingDetails()
        if include_optional:
            return PricingDetails(
                base_charge = 56,
                cancel_penalty_amount = 56,
                cost_minimum = 56,
                cost_per_mile = 56,
                cost_per_minute = 56,
                currency = '',
                trust_and_service = 56
            )
        else:
            return PricingDetails(
        )
        """

    def testPricingDetails(self):
        """Test PricingDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
