# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cancellation_cost_error import CancellationCostError

class TestCancellationCostError(unittest.TestCase):
    """CancellationCostError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CancellationCostError:
        """Test CancellationCostError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CancellationCostError`
        """
        model = CancellationCostError()
        if include_optional:
            return CancellationCostError(
                amount = 56,
                currency = '',
                description = '',
                token = '',
                token_duration = 0,
                error = '',
                error_description = '',
                error_detail = [
                    {"lat":"(latitude) Missing required parameter in the query string"}
                    ]
            )
        else:
            return CancellationCostError(
                amount = 56,
                currency = '',
                description = '',
        )
        """

    def testCancellationCostError(self):
        """Test CancellationCostError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
