# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cost_estimate import CostEstimate

class TestCostEstimate(unittest.TestCase):
    """CostEstimate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CostEstimate:
        """Test CostEstimate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CostEstimate`
        """
        model = CostEstimate()
        if include_optional:
            return CostEstimate(
                cost_token = '',
                currency = '',
                display_name = '',
                estimated_cost_cents_max = 56,
                estimated_cost_cents_min = 56,
                estimated_distance_miles = 1.337,
                estimated_duration_seconds = 56,
                is_valid_estimate = True,
                primetime_confirmation_token = '',
                primetime_percentage = '',
                ride_type = 'lyft'
            )
        else:
            return CostEstimate(
        )
        """

    def testCostEstimate(self):
        """Test CostEstimate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
