# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.eta import Eta

class TestEta(unittest.TestCase):
    """Eta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Eta:
        """Test Eta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Eta`
        """
        model = Eta()
        if include_optional:
            return Eta(
                display_name = '',
                eta_seconds = 56,
                eta_seconds_max = 56,
                is_valid_estimate = True,
                ride_type = 'lyft'
            )
        else:
            return Eta(
        )
        """

    def testEta(self):
        """Test Eta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
