# coding: utf-8

"""
    Lyft

    Drive your app to success with Lyft's API

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@lyft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_ride(self) -> None:
        """Test case for cancel_ride

        Cancel a ongoing requested ride
        """
        pass

    def test_get_profile(self) -> None:
        """Test case for get_profile

        The user's general info
        """
        pass

    def test_get_ride(self) -> None:
        """Test case for get_ride

        Get the ride detail of a given ride ID
        """
        pass

    def test_get_ride_receipt(self) -> None:
        """Test case for get_ride_receipt

        Get the receipt of the rides.
        """
        pass

    def test_get_rides(self) -> None:
        """Test case for get_rides

        List rides
        """
        pass

    def test_new_ride(self) -> None:
        """Test case for new_ride

        Request a Lyft
        """
        pass

    def test_set_ride_destination(self) -> None:
        """Test case for set_ride_destination

        Update the destination of the ride
        """
        pass

    def test_set_ride_rating(self) -> None:
        """Test case for set_ride_rating

        Add the passenger's rating, feedback, and tip
        """
        pass


if __name__ == '__main__':
    unittest.main()
